name: Do something amazing with dynamic title

run-name: Do something amazing for ${{ inputs.custom_title_suffix }}

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      custom_title_suffix:
        description: 'Custom title suffix'
        required: true
        default: 'placeholder'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Hello, World!
        run: echo "Hello, World!"
