name: Do something amazing with dynamic title

run-name: >-
  ${{ contains(inputs.custom_title_suffix, 'ci-systems')
    && format('Do something amazing for [CI] {0}', inputs.custom_title_suffix)
    || format('Do something amazing for [No CI] {0}', inputs.custom_title_suffix) }}

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      custom_title_suffix:
        description: 'Custom title suffix'
        required: true
        default: 'placeholder'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Hello, World!
        run: echo "Hello, World!"
